name: Go Format and Tidy

on:
  pull_request:
    branches: [ dev ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  format:
    name: Format and Tidy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Run go mod tidy
        run: go mod tidy

      - name: Run go fmt
        run: |
          go fmt ./...
          echo "Go code formatted"

      - name: Check for changes
        id: git-check
        run: |
          if git diff --exit-code; then
            echo "No changes to commit"
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Auto: run go mod tidy and go fmt"
          git push
